### ISSUE TITLE
I would like to compile the code in Arduino

### ISSUE THREAD

**Issue by Arakistech** [sparkfun/OpenLog_Artemis_Geophone_Logger#1]
I select Apollo3 board in board manager, but get this error: Compilation error: no matching function for call to 'arduino::MbedI2C::MbedI2C(int)'

**Comment by PaulZC** [comment]
Hi @Arakistech ,

This code is a few years old and has not been updated for the latest Apollo3 core.

You should be able to compile it if you install an older version of the SparkFun Apollo3 Boards. I suggest trying version 2.0.6 first.

Best wishes,
Paul

**Comment by PaulZC** [comment]
Hi @Arakistech ,

Apologies for the very long delay... This firmware has been updated to use v2.2.1 of the SparkFun Apollo3 core. Please see the release notes for more details:

https://github.com/sparkfun/OpenLog_Artemis_Geophone_Logger/releases/tag/v2.0

Best wishes,
Paul
